[info]
url = ""
listen_host = "127.0.0.1"
listen_port = 8085
mnemonic = ""
# input_fee_ppk = 0

[mint_info]
# name = "cdk-mintd mutiney net mint"
# Hex pubkey of mint
# pubkey = ""
# description = "These are not real sats for testing only"
# description_long = "A longer mint for testing"
# motd = "Hello world"
# icon_url = "https://this-is-a-mint-icon-url.com/icon.png"
# contact_email = "hello@cashu.me"
# Nostr pubkey of mint (Hex)
# contact_nostr_public_key = ""

[ln]
# fee_percent=0.04
# reserve_fee_min=4

[cln]
# Required if using cln backend path to rpc
rpc_path = "/var/lib/clightning/bitcoin/lightning-rpc"
bolt12 = true
fee_percent=0.02
reserve_fee_min=1

[SearchSettings]
cashu_secret_key=""
kagi_auth_token=""

