name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  self-care:
    name: Flake self-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v7
        with:
          fail-mode: true

  pre-commit-checks:
    name: "Pre-commit checks: cargo fmt, typos"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v11
      - name: Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v6
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Pre-commit checks
        run: nix develop -i -L .#stable --command pre-commit run --all-files

  clippy:
    name: "Stable build, clippy and test"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v11
      - name: Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v6
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: nix develop -i -L .#stable --command cargo build
      - name: Clippy
        run: nix develop -i -L .#stable --command cargo clippy -- -D warnings
